path: C:/Users/SARVESH/Desktop/repos/ICDEC_2024_Challenge
train: ../images/train
val: ../images/train

#classes 
names:
  0: car
  1: bike
  2: auto
  3: rickshaw
  4: cycle
  5: bus
  6: minitruck
  7: truck
  8: van
  9: taxi
  10: motorvan
  11: toto
  12: train
  13: boat
  14: other